---
namespace: iamgini
name: compliance
version: 0.1.0
readme: README.md
authors:
  - Gineesh Madapparambath
description: >
  Community Ansible collection for automated security compliance scanning
  and remediation using OpenSCAP and ComplianceAsCode. Supports Linux,
  Windows (future), and network devices (future).
license:
  - Apache-2.0
tags:
  - security
  - compliance
  - openscap
  - hardening
  - cis
  - stig
  - scap
repository: https://github.com/ginigangadharan/ansible-collection-compliance
documentation: https://github.com/ginigangadharan/ansible-collection-compliance/wiki
homepage: https://github.com/ginigangadharan/ansible-collection-compliance
issues: https://github.com/ginigangadharan/ansible-collection-compliance/issues
