---
- name: Parse OpenSCAP results and extract failed rules
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: false
  collections:
    - iamgini.compliance

  roles:
    - role: iamgini.compliance.parse_results
