---
galaxy_info:
  role_name: report_server
  author: Gineesh Madapparambath
  description: Set up nginx-based static report server for compliance scan results
  company: Community
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Fedora
      versions:
        - 38
        - 39
    - name: Ubuntu
      versions:
        - 22.04
        - 24.04
    - name: Debian
      versions:
        - 11
        - 12
  galaxy_tags:
    - security
    - compliance
    - reporting
    - nginx
    - web

dependencies: []
